import { Dialog, DialogContent } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { X } from "lucide-react";
import TransactionHistory from "./TransactionHistory";
import CollectionStatus from "./CollectionStatus";

interface NFTDetailModalProps {
  open?: boolean;
  onClose?: () => void;
  nft?: {
    id: string;
    name: string;
    image: string;
    price: number;
    collection: string;
    rarity: string;
    description?: string;
  };
}

const defaultNFT = {
  id: "1",
  name: "Purple Punk #1",
  image: "https://dummyimage.com/600x600/6b46c1/ffffff&text=NFT",
  price: 1000,
  collection: "Purple Punks",
  rarity: "Rare",
  description:
    "A unique NFT from the Purple Punks collection featuring distinctive artwork generated by AI.",
};

const NFTDetailModal = ({
  open = true,
  onClose = () => {},
  nft = defaultNFT,
}: NFTDetailModalProps) => {
  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="bg-white max-w-[600px] max-h-[800px] overflow-y-auto p-0">
        <div className="sticky top-0 bg-white z-10 p-4 border-b border-gray-200">
          <div className="flex justify-between items-center">
            <h2 className="text-2xl font-bold">{nft.name}</h2>
            <Button
              variant="ghost"
              size="icon"
              className="h-8 w-8"
              onClick={onClose}
            >
              <X className="h-4 w-4" />
            </Button>
          </div>
        </div>

        <div className="p-4 space-y-6">
          <div className="relative w-full aspect-square rounded-lg overflow-hidden">
            <img
              src={nft.image}
              alt={nft.name}
              className="w-full h-full object-cover"
            />
            <div className="absolute top-4 right-4 bg-purple-600 text-white px-3 py-1 rounded-full text-sm font-medium">
              {nft.rarity}
            </div>
          </div>

          <div className="space-y-4">
            <div>
              <h3 className="text-lg font-semibold">Description</h3>
              <p className="text-gray-600 mt-1">{nft.description}</p>
            </div>

            <div>
              <h3 className="text-lg font-semibold">Price</h3>
              <p className="text-2xl font-bold text-purple-600 mt-1">
                {nft.price.toLocaleString()} PC
              </p>
            </div>

            <div>
              <h3 className="text-lg font-semibold mb-2">Collection Status</h3>
              <CollectionStatus collectionName={nft.collection} />
            </div>

            <div>
              <h3 className="text-lg font-semibold mb-2">
                Transaction History
              </h3>
              <TransactionHistory />
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default NFTDetailModal;
